source "https://rubygems.org"

gem "sinatra", require: false
gem "sinatra-contrib", require: false
gem "poncho"

gem "trinidad", require: false

group :test do
  gem "guard-rspec"
  gem "rspec"
  gem "rack-test"
end
